COMMENT =		Gajim's fork of py-axolotl

MODPY_DISTV =		1.2.0
DISTNAME =		omemo_dr-${MODPY_DISTV}
PKGNAME =		py-omemo-dr-${MODPY_DISTV}

CATEGORIES =		security

# GPLv3
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

RUN_DEPENDS =		devel/py-protobuf>=4.21.0 \
			security/py-cryptography

.include <bsd.port.mk>
