COMMENT = Another Main Loop

V =	1.0.0
PKGNAME =	aml-$V
COMMIT =        c5a8bad585e4529a4e178589af30110326bf9df6
DIST_TUPLE =    github any1 aml ${COMMIT} .

SHARED_LIBS =	aml 0.0 # 1.0.0

CATEGORIES =	devel

# MIT
PERMIT_PACKAGE = Yes

WANTLIB =	pthread

MODULES =	devel/meson

COMPILER =	base-clang ports-gcc

.include <bsd.port.mk>
