COMMENT =		highly legible font designed for aircraft cockpits

MODFONT_FAMILY =	b612
MODFONT_VERSION =	1.008

GH_ACCOUNT =		polarsys
GH_PROJECT =		b612
GH_TAGNAME =		${MODFONT_VERSION}
PKGNAME =		b612-font-${GH_TAGNAME}

MODULES =		font

MAINTAINER =		Kurt Mosiejczuk <kmos@openbsd.org>

HOMEPAGE =		https://b612-font.com/

# OFL 1.1
PERMIT_PACKAGE =	Yes

NO_BUILD =		Yes
NO_TEST =		Yes

MODFONT_FONTFILES =	fonts/ttf/*.ttf

.include <bsd.port.mk>
