MODGO_MODULES =	\
	github.com/creack/pty		 v1.1.21 \
	github.com/davecgh/go-spew	 v1.1.1 \
	github.com/google/go-cmp	 v0.6.0 \
	github.com/gorilla/websocket	 v1.4.1 \
	github.com/mattn/go-isatty	 v0.0.20 \
	github.com/pmezard/go-difflib	 v1.0.0 \
	github.com/sourcegraph/jsonrpc2	 v0.2.0 \
	github.com/stretchr/testify	 v1.8.1 \
	go.etcd.io/bbolt		 v1.3.9 \
	go.etcd.io/gofail		 v0.1.0 \
	golang.org/x/sync		 v0.6.0 \
	golang.org/x/sys		 v0.17.0 \
	gopkg.in/yaml.v3		 v3.0.1 \
	pkg.nimblebun.works/go-lsp	 v1.1.0

MODGO_MODFILES =	\
	golang.org/x/sync	 v0.5.0 \
	golang.org/x/sys	 v0.4.0 \
	golang.org/x/sys	 v0.6.0

